project:
  type: website
  render:
    - pakicetus-stockA/pakicetus-stockA.qmd
    - pakicetus-stockB/pakicetus-stockB.qmd

website:
  title: "Marine Mammal Stock Assessment Report - IN DEVELOPMENT"
  navbar:
    left:
      - file: pakicetus-stockA/pakicetus-stockA.qmd
        text: Pakicetus - Stock A
      - file: pakicetus-stockB/pakicetus-stockB.qmd
        text: Pakicetus - Stock B

format:
  html:
    theme:
      - cosmo
      - assets/sar_theme.scss
    toc: true
