project:
  type: website
  render:
    - sf_pilot_whale_WNAstock/sf_pilot_whale_WNAstock.qmd

website:
  title: "SHORT-FINNED PILOT WHALE (_Globicephala macrorhynchus_): Western North Atlantic Stock - IN DEVELOPMENT"
  navbar:
    left:
      - file: sf_pilot_whale_WNAstock/sf_pilot_whale_WNAstock.qmd
        text: Short Finned Pilot Whale - Western North Atlantic Stock


format:
  html:
    theme:
      - cosmo
      - assets/sar_theme.scss
    toc: true
