---
title: "Pakicetus Stock A"
subtitle: "_Pakicetus sp_"
date: today
publication-date: 2050-01-01
date-format: "MMMM DD, YYYY"
citeproc: true
bibliography: ../assets/references_pakicetus.yaml
csl: ../assets/apa.csl

author:
  - name: Carl Linnaeus
    email: carl.linnaeus@noaa.gov
    orcid: 0000-0001-111-1111
    affiliations:
      - ref: 1
  - name: Charles Darwin
    email: charles.darwin@noaa.gov
    affiliations:
      - ref: 1

affiliations:
  - id: 1
    name: Alaska Fisheries Science Center
    department: National Marine Fisheries Service
    address: 7600 Sand Point Way NE
    city: Seattle
    state: WA

execute: 
  echo: false
  warning: false
  message: false

format:
  html: 
    out-width: "90%"
    fig-width: 9
    fig-asp: 0.618
  nmfs-sar-pdf-typst:
    nmfs-region: World
    sar-year: 2025
    stock-name: "Stock A"
    common-name: "Pakicetus"
    genus-species: "Pakicetus sp."
    linenumbering: true
    keep-typ: false
    fig-width: 9
    fig-asp: 0.618
    fig-dpi: 600
---

```{r}
#| label: setup
#| include: false

library(dplyr)
library(ggplot2)
library(purrr)
library(fs)

# source all R scripts in the R/ folder
r_files <- fs::dir_ls(here::here("R"), glob = "*.R")
purrr::map(r_files, source)

# set the image device to ragg_png for better quality plots
knitr::opts_chunk$set(dev = "ragg_png")

knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE
)

# make sure large numbers in text are formatted with commas
knitr::knit_hooks$set(
  inline = function(x) {
    if (!is.numeric(x)) {
      x
    } else {
      prettyNum(x, big.mark = ",")
    }
  }
)

options(scipen = 3, digits = 2)

# set the ggplot theme base font size and font family
theme_set(theme_minimal(base_size = 12, base_family = "Roboto"))

# function (for gt tables) to format numbers based on GAMMS specs
fmt_gamms_numbers <- function(x) {
  case_when(
    x <= 1 ~ formatC(x, format = "f", digits = 2),
    x > 1 & x <= 10 ~ formatC(x, format = "f", digits = 1),
    x > 10 ~ formatC(x, format = "f", digits = 0, big.mark = ","),
    TRUE ~ "format error"
  )
}
```

## STOCK DEFINITION AND GEOGRAPHIC RANGE

This section should summarize stock designation and DIP delineation information.
This information should include a summary of the lines of evidence that support
DIP delineations, and cite any supporting documents where this information is
detailed. This section should also include a description of what is known about
the geographic range of the stock (and a map if appropriate), including any
known stock boundaries if applicable, and any uncertainty regarding the stock
range. See Section 3.1 for additional guidance.

## POPULATION SIZE

This section should describe what is known about the size of the stock. It
should include specific sub headings entitled “Minimum Population Estimate” and
“Current Population Trend” describing these two characteristics of the stock. It
may include additional sub headings as appropriate such as “Earlier abundance
estimates”, “Recent surveys and abundance estimates”, and “Historical
abundance”, among others. See Section 3.2.1 and 3.2.2 for additional guidance.

## CURRENT AND MAXIMUM NET PRODUCTIVITY RATES

This section should describe what is known about the current and maximum net
productivity rates. Default values should be used for Rmax in the absence of
stock-specific measured values. See Section 3.2.3 for additional guidance.

## POTENTIAL BIOLOGICAL REMOVAL

This section of the SAR should provide a summary of the values used to calculate
PBR and details its calculation. See Section 3.2 for additional guidance.

## ANNUAL HUMAN-CAUSED MORTALITY AND SERIOUS INJURY

This section should contain a complete description of what is known about
human-caused M/SI for the covered time period. It should include a specific sub
heading entitled “Fisheries Information” that describes fishery-related M/SI and
may include other sub headings as appropriate, such as “Alaska Native
Subsistence/Harvest Information”, and “Other Mortality”, among others. See
Section 3.3 for additional guidance.

## STATUS OF STOCK

This section should summarize four types of “status” of the stock: (1) current
legal designation under the MMPA and ESA, (2) status relative to OSP (within
OSP, below OSP, or unknown), (3) designation of strategic or not, and (4) a
summary of trends in abundance and human-caused M/SI. See Section 3.4 for
additional guidance.

## OTHER FACTORS THAT MAY BE CAUSING A DECLINE OR IMPEDING RECOVERY

This section, which is required for strategic stocks but otherwise optional,
should describe any other factors affecting the status of the stock. It should
only be a summary of the issue and should reference publications. See Section
3.5 for additional guidance.

## REFERENCES CITED